version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: user_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: users_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    image: alfzuck1/exercise1:v2
    container_name: exercise1_api
    restart: always
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://user_database:3306/users_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  db_data: